#!/bin/bash

if [ $# -lt 1 ]; then 
    echo "Give bluetooth name of the (paired) phone you wish to tether"; exit; 
fi

# trap ctrl-c by calling ctrl_c()
trap ctrl_c INT

# exit tasks (when leaving wvdial through ctrl-C)
function ctrl_c() {
    echo "Releasing rfcomm"
    sudo rfcomm release 0 # we only bind 0 but we can also do "release all"
    echo "Reactivating network manager"
    sudo service NetworkManager start
    echo "Shutting down bluetooth"
    sudo rfkill block bluetooth # bt off
}

echo "Shutting down network manager"
sudo service NetworkManager stop
echo "Activating bluetooth"
sudo rfkill unblock bluetooth # bt on, in case it is not
echo "Getting bluetooth address of phone"
tmp=$(bluetoothctl paired-devices|grep $1)
tmp=${tmp#Device }
bt_address=${tmp%" $1"}
echo "Getting dial-up channel"
bt_channel=""
while [ "$bt_channel" == "" ]; do
    tmp=$(sdptool search --bdaddr "$bt_address" DUN|grep Channel) 
    bt_channel=${tmp#*: } 
done
echo "Binding rfcomm"
sudo rfcomm bind 0 "$bt_address" "$bt_channel"
echo "Tethering $1 ($bt_address/$bt_channel)"
wvdial bluetooth
